#-----------------------------------------------------------------------------------------------
# PROFILE LOCAL
#-----------------------------------------------------------------------------------------------
spring:
  profiles: local

#------------------------------
# ACTUATOR PROPERTIES
#------------------------------
# ENDPOINTS WEB CONFIGURATION
# - https://github.com/spring-projects/spring-boot/blob/v2.0.6.RELEASE/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/endpoint/web/WebEndpointProperties.java
management:
  endpoints.web:
    exposure.include: '*' # Endpoint IDs that should be included or '*' for all.
    exposure.exclude:  # Endpoint IDs that should be excluded or '*' for all.
    base-path: /admin # Base path for Web endpoints. Relative to server.servlet.context-path or management.server.servlet.context-path if management.server.port is configured.
    path-mapping.health: health

  # HEALTH ENDPOINT
  # - https://github.com/spring-projects/spring-boot/blob/v2.0.6.RELEASE/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/HealthEndpoint.java
  # - https://github.com/spring-projects/spring-boot/blob/v2.0.6.RELEASE/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/health/HealthEndpointProperties.java
  endpoint:
    health.cache.time-to-live: 0ms # Maximum time that a response can be cached.
    endpoint.health:
      enabled: true # Whether to enable the health endpoint.
      roles:  # Roles used to determine whether or not a user is authorized to be shown details. When empty, all authenticated users are authorized.
      show-details: always # When to show full health details.

  # INFO CONTRIBUTORS (InfoContributorProperties)
  info:
    build.enabled: true # Whether to enable build info.
    defaults.enabled: true # Whether to enable default info contributors.
    env.enabled: true # Whether to enable environment info.
    git:
      enabled: true # Whether to enable git info.
      mode: full # Mode to use to expose git information.
